# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@faker-js/faker@10.1.0" = fetchurl {
    url = "https://registry.npmjs.org/@faker-js/faker/-/faker-10.1.0.tgz";
    hash = "sha512-C3mrr3b5dRVlKPJdfrAXS8+dq+rq8Qm5SNRazca0JKgw1HQERFmrVb0towvMmw5uu8hHKNiQasMaR/tydf3Zsg==";
  };
  "@kwsites/file-exists@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@kwsites/file-exists/-/file-exists-1.1.1.tgz";
    hash = "sha512-m9/5YGR18lIwxSFDwfE3oA7bWuq9kdau6ugN4H2rJeyhFQZcG9AgSHkQtSD15a8WvTgfz9aikZMrKPHvbpqFiw==";
  };
  "@kwsites/promise-deferred@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@kwsites/promise-deferred/-/promise-deferred-1.1.1.tgz";
    hash = "sha512-GaHYm+c0O9MjZRu0ongGBRbinu8gVAMd2UZjji6jVmqKtZluZnptXGWhz1E8j8D2HJ3f/yMxKAUC0b+57wncIw==";
  };
  "@opencode-ai/plugin@1.0.143" = fetchurl {
    url = "https://registry.npmjs.org/@opencode-ai/plugin/-/plugin-1.0.143.tgz";
    hash = "sha512-yzaCmdazVJMDADJLbMM8KGp1X+Hd/HVyIXMlNt9qcvz/fcs/ET4EwHJsJaQi/9m/jLJ+plwBJAeIW08BMrECPg==";
  };
  "@opencode-ai/sdk@1.0.143" = fetchurl {
    url = "https://registry.npmjs.org/@opencode-ai/sdk/-/sdk-1.0.143.tgz";
    hash = "sha512-dtmkBfJ7IIAHzL6KCzAlwc9GybfJONVeCsF6ePYySpkuhslDbRkZBJYb5vqGd1H5zdsgjc6JjuvmOf0rPWUL6A==";
  };
  "@opencodium/auto-worktree" = copyPathToStore ./packages/auto-worktree;
  "@opencodium/bash-wrapper" = copyPathToStore ./packages/bash-wrapper;
  "@opencodium/dyn-sym" = copyPathToStore ./packages/dyn-sym;
  "@opencodium/git-narration" = copyPathToStore ./packages/git-narration;
  "@opencodium/shared" = copyPathToStore ./packages/shared;
  "@opencodium/skills" = copyPathToStore ./packages/skills;
  "@types/bun@1.3.4" = fetchurl {
    url = "https://registry.npmjs.org/@types/bun/-/bun-1.3.4.tgz";
    hash = "sha512-EEPTKXHP+zKGPkhRLv+HI0UEX8/o+65hqARxLy8Ov5rIxMBPNTjeZww00CIihrIQGEQBYg+0roO5qOnS/7boGA==";
  };
  "@types/diff@7.0.2" = fetchurl {
    url = "https://registry.npmjs.org/@types/diff/-/diff-7.0.2.tgz";
    hash = "sha512-JSWRMozjFKsGlEjiiKajUjIJVKuKdE3oVy2DNtK+fUo8q82nhFZ2CPQwicAIkXrofahDXrWJ7mjelvZphMS98Q==";
  };
  "@types/node@25.0.0" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-25.0.0.tgz";
    hash = "sha512-rl78HwuZlaDIUSeUKkmogkhebA+8K1Hy7tddZuJ3D0xV8pZSfsYGTsliGUol1JPzu9EKnTxPC4L1fiWouStRew==";
  };
  "argparse@1.0.10" = fetchurl {
    url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
    hash = "sha512-o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
  };
  "bun-types@1.3.4" = fetchurl {
    url = "https://registry.npmjs.org/bun-types/-/bun-types-1.3.4.tgz";
    hash = "sha512-5ua817+BZPZOlNaRgGBpZJOSAQ9RQ17pkwPD0yR7CfJg+r8DgIILByFifDTa+IPDDxzf5VNhtNlcKqFzDgJvlQ==";
  };
  "debug@4.4.3" = fetchurl {
    url = "https://registry.npmjs.org/debug/-/debug-4.4.3.tgz";
    hash = "sha512-RGwwWnwQvkVfavKVt22FGLw+xYSdzARwm0ru6DhTVA3umU5hZc28V3kO4stgYryrTlLpuvgI9GiijltAjNbcqA==";
  };
  "diff@7.0.0" = fetchurl {
    url = "https://registry.npmjs.org/diff/-/diff-7.0.0.tgz";
    hash = "sha512-PJWHUb1RFevKCwaFA9RlG5tCd+FO5iRh9A8HEtkmBH2Li03iJriB6m6JIN4rGz3K3JLawI7/veA1xzRKP6ISBw==";
  };
  "esprima@4.0.1" = fetchurl {
    url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
    hash = "sha512-eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
  };
  "extend-shallow@2.0.1" = fetchurl {
    url = "https://registry.npmjs.org/extend-shallow/-/extend-shallow-2.0.1.tgz";
    hash = "sha512-zCnTtlxNoAiDc3gqY2aYAWFx7XWWiasuF2K8Me5WbN8otHKTUKBwjPtNpRs/rbUZm7KxWAaNj7P1a/p52GbVug==";
  };
  "gray-matter@4.0.3" = fetchurl {
    url = "https://registry.npmjs.org/gray-matter/-/gray-matter-4.0.3.tgz";
    hash = "sha512-5v6yZd4JK3eMI3FqqCouswVqwugaA9r4dNZB1wwcmrD02QkV5H0y7XBQW8QwQqEaZY1pM9aqORSORhJRdNK44Q==";
  };
  "is-extendable@0.1.1" = fetchurl {
    url = "https://registry.npmjs.org/is-extendable/-/is-extendable-0.1.1.tgz";
    hash = "sha512-5BMULNob1vgFX6EjQw5izWDxrecWK9AM72rugNr0TFldMOi0fj6Jk+zeKIt0xGj4cEfQIJth4w3OKWOJ4f+AFw==";
  };
  "js-yaml@3.14.2" = fetchurl {
    url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.14.2.tgz";
    hash = "sha512-PMSmkqxr106Xa156c2M265Z+FTrPl+oxd/rgOQy2tijQeK5TxQ43psO1ZCwhVOSdnn+RzkzlRz/eY4BgJBYVpg==";
  };
  "kind-of@6.0.3" = fetchurl {
    url = "https://registry.npmjs.org/kind-of/-/kind-of-6.0.3.tgz";
    hash = "sha512-dcS1ul+9tmeD95T+x28/ehLgd9mENa3LsvDTtzm3vyBEO7RPptvAD+t44WVXaUjTBRcrpFeFlC8WCruUR456hw==";
  };
  "ms@2.1.3" = fetchurl {
    url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
    hash = "sha512-6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
  };
  "section-matter@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/section-matter/-/section-matter-1.0.0.tgz";
    hash = "sha512-vfD3pmTzGpufjScBh50YHKzEu2lxBWhVEHsNGoEXmCmn2hKGfeNLYMzCJpe8cD7gqX7TJluOVpBkAequ6dgMmA==";
  };
  "simple-git@3.30.0" = fetchurl {
    url = "https://registry.npmjs.org/simple-git/-/simple-git-3.30.0.tgz";
    hash = "sha512-q6lxyDsCmEal/MEGhP1aVyQ3oxnagGlBDOVSIB4XUVLl1iZh0Pah6ebC9V4xBap/RfgP2WlI8EKs0WS0rMEJHg==";
  };
  "sprintf-js@1.0.3" = fetchurl {
    url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
    hash = "sha512-D9cPgkvLlV3t3IzL0D0YLvGA9Ahk4PcvVwUbN0dSGr1aP0Nrt4AEnTUbuGvquEC0mA64Gqt1fzirlRs5ibXx8g==";
  };
  "strip-bom-string@1.0.0" = fetchurl {
    url = "https://registry.npmjs.org/strip-bom-string/-/strip-bom-string-1.0.0.tgz";
    hash = "sha512-uCC2VHvQRYu+lMh4My/sFNmF2klFymLX1wHJeXnbEJERpV/ZsVuonzerjfrGpIGF7LBVa1O7i9kjiWvJiFck8g==";
  };
  "typescript@5.9.3" = fetchurl {
    url = "https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz";
    hash = "sha512-jl1vZzPDinLr9eUt3J/t7V6FgNEw9QjvBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wtm6M5TgSw==";
  };
  "undici-types@7.16.0" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-7.16.0.tgz";
    hash = "sha512-Zz+aZWSj8LE6zoxD+xrjh4VfkIG8Ya6LvYkZqtUQGJPZjYl53ypCaUwWqo7eI0x66KBGeRo+mlBEkMSeSZ38Nw==";
  };
  "xdg-basedir@5.1.0" = fetchurl {
    url = "https://registry.npmjs.org/xdg-basedir/-/xdg-basedir-5.1.0.tgz";
    hash = "sha512-GCPAHLvrIH13+c0SuacwvRYj2SxJXQ4kaVTT5xgL3kPrz56XxkF21IGhjSE1+W0aw7gpBWRGXLCPnPby6lSpmQ==";
  };
  "zod@3.25.76" = fetchurl {
    url = "https://registry.npmjs.org/zod/-/zod-3.25.76.tgz";
    hash = "sha512-gzUt/qt81nXsFGKIFcC3YnfEAx5NkunCfnDlvuBSSFS02bcXu4Lmea0AFIUwbLWxWPx3d9p8S5QoaujKcNQxcQ==";
  };
  "zod@4.1.13" = fetchurl {
    url = "https://registry.npmjs.org/zod/-/zod-4.1.13.tgz";
    hash = "sha512-AvvthqfqrAhNH9dnfmrfKzX5upOdjUVJYFqNSlkmGf64gRaTzlPwz99IHYnVs28qYAybvAlBV+H7pn0saFY4Ig==";
  };
  "zod@4.1.8" = fetchurl {
    url = "https://registry.npmjs.org/zod/-/zod-4.1.8.tgz";
    hash = "sha512-5R1P+WwQqmmMIEACyzSvo4JXHY5WiAFHRMg+zBZKgKS+Q1viRa0C1hmUKtHltoIFKtIdki3pRxkmpP74jnNYHQ==";
  };
}